# Generated by Django 4.2.5 on 2023-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('slug', models.SlugField(max_length=7, unique_for_date='created_at')),
                ('link', models.CharField(max_length=250)),
                ('rotation_time', models.DecimalField(decimal_places=2, max_digits=3)),
                ('revolution_time', models.DecimalField(decimal_places=2, max_digits=3)),
                ('radius', models.IntegerField()),
                ('average_temp', models.IntegerField()),
                ('overview', models.TextField()),
                ('overview_img', models.ImageField(upload_to='uploads/')),
                ('internal_structure', models.TextField()),
                ('internal_structure_img', models.ImageField(upload_to='uploads/')),
                ('surface_geology', models.TextField()),
                ('surface_geology_img', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='planets_pla_created_fa39b3_idx')],
            },
        ),
    ]
