# Generated by Django 4.2.5 on 2023-09-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_alter_planet_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='radius',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='planet',
            name='revolution_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='planet',
            name='rotation_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
